# Generated by Django 3.2.24 on 2025-04-24 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('hora_ped', models.DateTimeField()),
                ('hora_ent', models.DateTimeField()),
                ('observaciones', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cc', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('dir', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=6)),
                ('modelo', models.IntegerField()),
                ('marca', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=255)),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.usuario')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nit', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('propietario', models.CharField(max_length=50)),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=9)),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='prueba.PedidoProducto', to='prueba.Producto'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_red', models.CharField(max_length=255)),
                ('id_pedido', models.IntegerField()),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CEDI',
            fields=[
                ('id_bod', models.IntegerField(primary_key=True, serialize=False)),
                ('coord', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.pedido')),
            ],
        ),
    ]
